// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHj32DdqjxBmNLBgKgTUQ6u5_FR1HLn5A',
    appId: '1:850311561242:web:58e27e601cbc8683cc91a3',
    messagingSenderId: '850311561242',
    projectId: 'bbmp-reporter',
    authDomain: 'bbmp-reporter.firebaseapp.com',
    storageBucket: 'bbmp-reporter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCImStQ8jN08fKqT5lTTYV5KCvoqXtJHxY',
    appId: '1:850311561242:android:f6412d5f8ffa0da1cc91a3',
    messagingSenderId: '850311561242',
    projectId: 'bbmp-reporter',
    storageBucket: 'bbmp-reporter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3Lg6GLQ78i1L1mcY-ha_Ko0q5eg0SLg',
    appId: '1:850311561242:ios:c72cadc56a8b7f01cc91a3',
    messagingSenderId: '850311561242',
    projectId: 'bbmp-reporter',
    storageBucket: 'bbmp-reporter.appspot.com',
    iosBundleId: 'com.example.bbmpReporter',
  );
}
